// GENERATED — do not edit by hand.
// Built by scripts/build-idioms.mjs from scripts/data/idioms.csv
// (baiango/english_idioms, The Unlicense — public domain).
// Idiom -> plain-English paraphrase pairs stacked into the free-MT
// pre-edit defaults. IDIOM_PATTERNS[i] is a regex source matched with
// the 'gi' flags inside (?<!\w)...(?!\w); IDIOM_REPLACEMENTS[i] is its
// plain substitute. Order is longest-pattern-first. IDIOM_HEAD_BASE[i] is
// the lowercase base head word ("" when not inflectable), used for tense
// agreement at runtime.
export const IDIOM_PATTERNS: string[] = [
  "hear(?:s|es|ed|ing)? \\w+ straight from the horse's mouth",
  "(?:got|Get(?:s|es|ed|ing)?) a taste of your own medicine",
  "(?:flew|Fly(?:s|es|ed|ing)?) by the seat of your pants",
  "Cross(?:s|es|ed|ing)? that bridge when you come to it",
  "(?:fell|Fall(?:s|es|ed|ing)?) off the back of a lorry",
  "Count(?:s|es|ed|ing)? your chickens before they hatch",
  "(?:gave|Giv(?:e|es|ed|ing)) the benefit of the doubt",
  "Cross(?:s|es|ed|ing)? that bridge when we come to it",
  "(?:made|Mak(?:e|es|ed|ing)) hay while the sun shines",
  "(?:took|Tak(?:e|es|ed|ing)) it with a grain of salt",
  "(?:went|Going(?:s|es|ed|ing)?) the whole nine yards",
  "(?:stole|Steal(?:s|es|ed|ing)?) \\w+(?:'s)? thunder",
  "Put(?:s|es|ed|ing)? your money where your mouth is",
  "(?:gave|Giv(?:e|es|ed|ing)) \\w+ the cold shoulder",
  "(?:took|Tak(?:e|es|ed|ing)) with a grain of salt",
  "(?:broke|Break(?:s|es|ed|ing)?) \\w+(?:'s)? heart",
  "Keep(?:s|es|ed|ing)? your nose to the grindstone",
  "Put(?:s|es|ed|ing)? all your eggs in one basket",
  "(?:got|Get(?:s|es|ed|ing)?) down to brass tacks",
  "An ounce of prevention is worth a pound of cure",
  "Attract(?:s|es|ed|ing)? attention like a magnet",
  "Cross(?:s|es|ed|ing)? your T's and dot your I's",
  "(?:rode|Rid(?:e|es|ed|ing)) off into the sunset",
  "(?:made|Mak(?:e|es|ed|ing)) a long story short",
  "(?:came|Com(?:e|es|ed|ing)) hell or high water",
  "Cross(?:s|es|ed|ing)? my heart and hope to die",
  "Wear(?:s|es|ed|ing)? your heart on your sleeve",
  "Open(?:s|es|ed|ing)? the door to possibilities",
  "Put(?:s|es|ed|ing)? your shoulder to the wheel",
  "Shout(?:s|es|ed|ing)? it from the mountaintops",
  "(?:broke|Break(?:s|es|ed|ing)?) bread together",
  "(?:drove|Driv(?:e|es|ed|ing)) \\w+ up the wall",
  "Kill(?:s|es|ed|ing)? two birds with one stone",
  "(?:came|Com(?:e|es|ed|ing)) out of your shell",
  "Put(?:s|es|ed|ing)? the cart before the horse",
  "(?:swam|Swim(?:s|es|ed|ing)?) with the sharks",
  "(?:broke|Break(?:s|es|ed|ing)?) in the clouds",
  "(?:rang|Ring(?:s|es|ed|ing)?) in the new year",
  "(?:went|Going(?:s|es|ed|ing)?) the extra mile",
  "(?:spoke|Speak(?:s|es|ed|ing)?) of the devil",
  "Feel(?:s|es|ed|ing)? a bit under the weather",
  "(?:got|Get(?:s|es|ed|ing)?) the ball rolling",
  "Open(?:s|es|ed|ing)? the door to opportunity",
  "(?:drove|Driv(?:e|es|ed|ing)) a hard bargain",
  "Read(?:s|es|ed|ing)? the writing on the wall",
  "(?:made|Mak(?:e|es|ed|ing)) a grand entrance",
  "Don't count your chickens before they hatch",
  "(?:flew|Fly(?:s|es|ed|ing)?) off the handle",
  "A bird in the hand is worth two in the bush",
  "(?:came|Com(?:e|es|ed|ing)) out in the wash",
  "(?:fell|Fall(?:s|es|ed|ing)?) on hard times",
  "Shout(?:s|es|ed|ing)? from the mountaintops",
  "Let(?:s|es|ed|ing)? the cat out of the bag",
  "We'll cross that bridge when we come to it",
  "(?:fell|Fall(?:s|es|ed|ing)?) on deaf ears",
  "(?:broke|Break(?:s|es|ed|ing)?) new ground",
  "Pull(?:s|es|ed|ing)? a rabbit out of a hat",
  "Put(?:s|es|ed|ing)? your best foot forward",
  "(?:made|Mak(?:e|es|ed|ing)) a house a home",
  "Mark(?:s|es|ed|ing)? the occasion joyfully",
  "Rain(?:s|es|ed|ing)? on \\w+(?:'s)? parade",
  "(?:ran|Run(?:s|es|ed|ing)?) like the wind",
  "Bird in the hand is worth two in the bush",
  "(?:came|Com(?:e|es|ed|ing)) rain or shine",
  "(?:drove|Driv(?:e|es|ed|ing)) up the wall",
  "(?:came|Com(?:e|es|ed|ing)) to grips with",
  "Pour(?:s|es|ed|ing)? out \\w+(?:'s)? heart",
  "Wrap(?:s|es|ed|ing)? your head around \\w+",
  "(?:spoke|Speak(?:s|es|ed|ing)?) your mind",
  "Keep(?:s|es|ed|ing)? your fingers crossed",
  "Hit(?:s|es|ed|ing)? the road of adventure",
  "Hit(?:s|es|ed|ing)? the nail on the head",
  "Hear(?:s|es|ed|ing)? it on the grapevine",
  "Turn(?:s|es|ed|ing)? a blind eye(?: to)?",
  "(?:sat|Sit(?:s|es|ed|ing)?) on the fence",
  "(?:ran|Run(?:s|es|ed|ing)?) out of steam",
  "(?:flew|Fly(?:s|es|ed|ing)?) on the wall",
  "(?:broke|Break(?:s|es|ed|ing)?) the mold",
  "(?:went|Going(?:s|es|ed|ing)?) for broke",
  "(?:took|Tak(?:e|es|ed|ing)) a rain check",
  "(?:broke|Break(?:s|es|ed|ing)?) the bank",
  "Tast(?:e|es|ed|ing) of your own medicine",
  "The apple doesn't fall far from the tree",
  "Compar(?:e|es|ed|ing) apples and oranges",
  "(?:took|Tak(?:e|es|ed|ing)) center stage",
  "Enjoy(?:s|es|ed|ing)? the great outdoors",
  "(?:spoke|Speak(?:s|es|ed|ing)?) out loud",
  "Put(?:s|es|ed|ing)? on your thinking cap",
  "Walk(?:s|es|ed|ing)? in \\w+ else's shoes",
  "Build(?:s|es|ed|ing)? a castle of dreams",
  "(?:stole|Steal(?:s|es|ed|ing)?) the show",
  "Crossing that bridge when you come to it",
  "You can't have your cake and eat it too",
  "(?:broke|Break(?:s|es|ed|ing)?) the ice",
  "Drastic times call for drastic measures",
  "(?:came|Com(?:e|es|ed|ing)) full circle",
  "Cut(?:s|es|ed|ing)? from the same cloth",
  "Getting up on the wrong side of the bed",
  "Between the devil and the deep blue sea",
  "Clos(?:e|es|ed|ing) the door behind you",
  "(?:rang|Ring(?:s|es|ed|ing)?) the alarm",
  "(?:broke|Break(?:s|es|ed|ing)?) of dawn",
  "Open(?:s|es|ed|ing)? the door carefully",
  "Handl(?:e|es|ed|ing) the door with care",
  "Embark(?:s|es|ed|ing)? on a fresh start",
  "Draw(?:s|es|ed|ing)? a line in the sand",
  "Shout(?:s|es|ed|ing)? from the rooftops",
  "Strik(?:e|es|ed|ing) a harmonious chord",
  "A pot of gold at the end of the rainbow",
  "Stay(?:s|es|ed|ing)? on the right track",
  "Read(?:s|es|ed|ing)? between the lines",
  "Feel(?:s|es|ed|ing)? under the weather",
  "(?:ate|Eat(?:s|es|ed|ing)?) humble pie",
  "Fight(?:s|es|ed|ing)? like cat and dog",
  "Caught between a rock and a hard place",
  "Wash(?:s|es|ed|ing)? your hands of \\w+",
  "Let(?:s|es|ed|ing)? bygones be bygones",
  "Hit(?:s|es|ed|ing)? the ground running",
  "(?:broke|Break(?:s|es|ed|ing)?) of day",
  "(?:made|Mak(?:e|es|ed|ing)) some noise",
  "(?:broke|Break(?:s|es|ed|ing)?) a leg",
  "Don't put all your eggs in one basket",
  "Roll(?:s|es|ed|ing)? with the punches",
  "Cry(?:s|es|ed|ing)? over spilled milk",
  "Jump(?:s|es|ed|ing)? on the bandwagon",
  "cost(?:s|es|ed|ing)? an arm and a leg",
  "Let(?:s|es|ed|ing)? sleeping dogs lie",
  "Burn(?:s|es|ed|ing)? the midnight oil",
  "Born on the wrong side of the blanket",
  "(?:came|Com(?:e|es|ed|ing)) a cropper",
  "(?:came|Com(?:e|es|ed|ing)) up trumps",
  "(?:went|Go) back to the drawing board",
  "Play(?:s|es|ed|ing)? your cards right",
  "Keep(?:s|es|ed|ing)? your eyes peeled",
  "Stop(?:s|es|ed|ing)? at the red light",
  "Cross(?:s|es|ed|ing)? the finish line",
  "Sing(?:s|es|ed|ing)? a different tune",
  "Leav(?:e|es|ed|ing) no stone unturned",
  "(?:broke|Break(?:s|es|ed|ing)?) bread",
  "(?:rode|Rid(?:e|es|ed|ing)) the waves",
  "Think(?:s|es|ed|ing)? outside the box",
  "Find(?:s|es|ed|ing)? your inner peace",
  "(?:saw|Se(?:e|es|ed|ing)) eye to eye",
  "Add(?:s|es|ed|ing)? insult to injury",
  "Keep(?:s|es|ed|ing)? a straight face",
  "Bring(?:s|es|ed|ing)? home the bacon",
  "An apple a day keeps the doctor away",
  "Beauty is in the eye of the beholder",
  "Fight(?:s|es|ed|ing)? tooth and nail",
  "Add(?:s|es|ed|ing)? fuel to the fire",
  "Call(?:s|es|ed|ing)? a spade a spade",
  "(?:got|Get(?:s|es|ed|ing)?) a leg up",
  "Twist(?:s|es|ed|ing)? \\w+(?:'s)? arm",
  "(?:rang|Ring(?:s|es|ed|ing)?) a bell",
  "(?:got|Get(?:s|es|ed|ing)?) in shape",
  "Not everything that glitters is gold",
  "Turn(?:s|es|ed|ing)? over a new leaf",
  "(?:rode|Rid(?:e|es|ed|ing)) the wave",
  "Find(?:s|es|ed|ing)? a silver lining",
  "Defend(?:s|es|ed|ing)? your position",
  "(?:rode|Rid(?:e|es|ed|ing)) the tide",
  "Bring(?:s|es|ed|ing)? the house down",
  "Mark(?:s|es|ed|ing)? on the calendar",
  "Finish(?:s|es|ed|ing)? line in sight",
  "Don't put the cart before the horse",
  "Pull(?:s|es|ed|ing)? \\w+(?:'s)? leg",
  "Cry(?:s|es|ed|ing)? over spilt milk",
  "You can't judge a book by its cover",
  "A picture is worth a thousand words",
  "Butter wouldn't melt in their mouth",
  "Cost(?:s|es|ed|ing)? a pretty penny",
  "(?:got|Get(?:s|es|ed|ing)?) wind of",
  "Absence makes the heart grow fonder",
  "Buy(?:s|es|ed|ing)? a pig in a poke",
  "Open(?:s|es|ed|ing)? a can of worms",
  "Shoot(?:s|es|ed|ing)? for the stars",
  "Open(?:s|es|ed|ing)? the floodgates",
  "Deliver(?:s|es|ed|ing)? the package",
  "Turn(?:s|es|ed|ing)? back the clock",
  "Reach(?:s|es|ed|ing)? for the stars",
  "Defend(?:s|es|ed|ing)? your beliefs",
  "Read(?:s|es|ed|ing)? the fine print",
  "Sing(?:s|es|ed|ing)? your heart out",
  "(?:made|Mak(?:e|es|ed|ing)) a scene",
  "Shar(?:e|es|ed|ing) a meal together",
  "Throw(?:s|es|ed|ing)? in the towel",
  "Drop(?:s|es|ed|ing)? in the bucket",
  "Cry(?:s|es|ed|ing)? your heart out",
  "Can't see the forest for the trees",
  "Don't bite the hand that feeds you",
  "Cross(?:s|es|ed|ing)? your fingers",
  "Shoot(?:s|es|ed|ing)? from the hip",
  "That's the way the cookie crumbles",
  "Rub(?:s|es|ed|ing)? shoulders with",
  "Sav(?:e|es|ed|ing) for a rainy day",
  "Rais(?:e|es|ed|ing) the white flag",
  "(?:took|Tak(?:e|es|ed|ing)) flight",
  "Put(?:s|es|ed|ing)? your foot down",
  "Shoot(?:s|es|ed|ing)? for the moon",
  "Rain(?:s|es|ed|ing)? on the parade",
  "March to the beat of your own drum",
  "Hit(?:s|es|ed|ing)? the right note",
  "Kick(?:s|es|ed|ing)? the door down",
  "The pen is mightier than the sword",
  "The light at the end of the tunnel",
  "Start(?:s|es|ed|ing)? of a new day",
  "Time flies when you're having fun",
  "Keep(?:s|es|ed|ing)? your chin up",
  "Birds of a feather flock together",
  "Drop(?:s|es|ed|ing)? in the ocean",
  "(?:came|Com(?:e|es|ed|ing)) clean",
  "Biting off more than you can chew",
  "Burn(?:s|es|ed|ing)? your bridges",
  "A picture paints a thousand words",
  "Hav(?:e|es|ed|ing) sticky fingers",
  "(?:made|Mak(?:e|es|ed|ing)) waves",
  "Stand(?:s|es|ed|ing)? your ground",
  "(?:flew|Fly(?:s|es|ed|ing)?) high",
  "Cross(?:s|es|ed|ing)? that bridge",
  "Read(?:s|es|ed|ing)? all about it",
  "Mark(?:s|es|ed|ing)? the calendar",
  "Put(?:s|es|ed|ing)? it in writing",
  "Finish(?:s|es|ed|ing)? line ahead",
  "Cut(?:s|es|ed|ing)? to the chase",
  "Hold(?:s|es|ed|ing)? your horses",
  "Clos(?:e|es|ed|ing) but no cigar",
  "Drop(?:s|es|ed|ing)? a bombshell",
  "Flying by the seat of your pants",
  "Cut(?:s|es|ed|ing)? to the quick",
  "Cry(?:s|es|ed|ing)? for the moon",
  "Draw(?:s|es|ed|ing)? first blood",
  "Chang(?:e|es|ed|ing) in the wind",
  "Put(?:s|es|ed|ing)? pen to paper",
  "Hit(?:s|es|ed|ing)? the bullseye",
  "Wish(?:s|es|ed|ing)? upon a star",
  "Celebrat(?:e|es|ed|ing) with joy",
  "Open(?:s|es|ed|ing)? the door to",
  "Mind(?:s|es|ed|ing)? over matter",
  "Sleep(?:s|es|ed|ing)? like a log",
  "Killing two birds with one stone",
  "Celebrat(?:e|es|ed|ing) in style",
  "Win(?:s|es|ed|ing)? at all costs",
  "Kick(?:s|es|ed|ing)? the bucket",
  "Actions speak louder than words",
  "Fit(?:s|es|ed|ing)? as a fiddle",
  "Bite off more than you can chew",
  "Don't judge a book by its cover",
  "Liv(?:e|es|ed|ing) and let live",
  "Spill(?:s|es|ed|ing)? the beans",
  "Every cloud has a silver lining",
  "The early bird catches the worm",
  "Between a rock and a hard place",
  "Keep(?:s|es|ed|ing)? \\w+ at bay",
  "Picture paints a thousand words",
  "Can't judge a book by its cover",
  "Cut(?:s|es|ed|ing)? the mustard",
  "Flat out like a lizard drinking",
  "A penny saved is a penny earned",
  "Burning the candle at both ends",
  "Giving the benefit of the doubt",
  "A rolling stone gathers no moss",
  "Everything but the kitchen sink",
  "Straight from the horse's mouth",
  "Clos(?:e|es|ed|ing) the door on",
  "Los(?:e|es|ed|ing) your marbles",
  "Sound(?:s|es|ed|ing)? the alarm",
  "End(?:s|es|ed|ing)? of the road",
  "Shin(?:e|es|ed|ing) like a star",
  "Learn(?:s|es|ed|ing)? the ropes",
  "Jump(?:s|es|ed|ing)? the tracks",
  "Keep(?:s|es|ed|ing)? an eye out",
  "Aim(?:s|es|ed|ing)? for success",
  "Carry(?:s|es|ed|ing)? the torch",
  "Clos(?:e|es|ed|ing) the book on",
  "Ris(?:e|es|ed|ing) with the sun",
  "Cry(?:s|es|ed|ing)? me a river",
  "Call(?:s|es|ed|ing)? the shots",
  "Catch(?:s|es|ed|ing)? your eye",
  "Find(?:s|es|ed|ing)? your feet",
  "Fit(?:s|es|ed|ing)? for a king",
  "Be the apple of \\w+(?:'s)? eye",
  "Chang(?:e|es|ed|ing) your tune",
  "Cook(?:s|es|ed|ing)? the books",
  "Light at the end of the tunnel",
  "Catch(?:s|es|ed|ing)? some Z's",
  "Rais(?:e|es|ed|ing) your voice",
  "Hit(?:s|es|ed|ing)? the target",
  "Play(?:s|es|ed|ing)? it by ear",
  "Carry(?:s|es|ed|ing)? the load",
  "Win(?:s|es|ed|ing)? hands down",
  "Achiev(?:e|es|ed|ing) the goal",
  "Kill(?:s|es|ed|ing)? two birds",
  "Chang(?:e|es|ed|ing) the world",
  "Rais(?:e|es|ed|ing) a red flag",
  "Letting the cat out of the bag",
  "Sound(?:s|es|ed|ing)? the horn",
  "Miss(?:s|es|ed|ing)? the boat",
  "Hit(?:s|es|ed|ing)? the books",
  "Your guess is as good as mine",
  "Call(?:s|es|ed|ing)? it a day",
  "Catch(?:s|es|ed|ing)? some Zs",
  "Draw(?:s|es|ed|ing)? the line",
  "Chang(?:e|es|ed|ing) of heart",
  "All that glitters is not gold",
  "Cry(?:s|es|ed|ing)? the blues",
  "Drop(?:s|es|ed|ing)? the ball",
  "Bark is worse than their bite",
  "Call(?:s|es|ed|ing)? it quits",
  "Carry(?:s|es|ed|ing)? the can",
  "Miss(?:s|es|ed|ing)? the mark",
  "Best thing since sliced bread",
  "(?:went|Go) around in circles",
  "Build(?:s|es|ed|ing)? bridges",
  "Roll(?:s|es|ed|ing)? the dice",
  "Slow and steady wins the race",
  "Put(?:s|es|ed|ing)? on a show",
  "Sav(?:e|es|ed|ing) your bacon",
  "Castaway on a deserted island",
  "Stay(?:s|es|ed|ing)? on track",
  "Turn(?:s|es|ed|ing)? the page",
  "Open(?:s|es|ed|ing)? the door",
  "A day late and a dollar short",
  "Twist(?:s|es|ed|ing)? of fate",
  "Chang(?:e|es|ed|ing) the tune",
  "Call(?:s|es|ed|ing)? the tune",
  "Don't put eggs in one basket",
  "Jump(?:s|es|ed|ing)? the gun",
  "Hit(?:s|es|ed|ing)? the sack",
  "Burn(?:s|es|ed|ing)? bridges",
  "Hit(?:s|es|ed|ing)? the road",
  "Not playing with a full deck",
  "Bite the hand that feeds you",
  "As fast as greased lightning",
  "Draw(?:s|es|ed|ing)? a blank",
  "For all intents and purposes",
  "A taste of your own medicine",
  "Hav(?:e|es|ed|ing) the blues",
  "Los(?:e|es|ed|ing) your cool",
  "Sink(?:s|es|ed|ing)? or swim",
  "Ris(?:e|es|ed|ing) and shine",
  "Fit(?:s|es|ed|ing)? the bill",
  "Set(?:s|es|ed|ing)? in stone",
  "Strik(?:e|es|ed|ing) a chord",
  "Hold(?:s|es|ed|ing)? the key",
  "Hit(?:s|es|ed|ing)? the hay",
  "A snowball's chance in hell",
  "Cut(?:s|es|ed|ing)? corners",
  "Elvis has left the building",
  "Butterflies in your stomach",
  "A stitch in time saves nine",
  "Blood is thicker than water",
  "Chip on \\w+(?:'s)? shoulder",
  "Rul(?:e|es|ed|ing) of thumb",
  "Buy(?:s|es|ed|ing)? a lemon",
  "Lend(?:s|es|ed|ing)? an ear",
  "Us(?:e|es|ed|ing) your head",
  "Hit(?:s|es|ed|ing)? the gas",
  "Rais(?:e|es|ed|ing) a glass",
  "Don't cry over spilled milk",
  "Early bird catches the worm",
  "The devil is in the details",
  "Like a kid in a candy store",
  "A feather in \\w+(?:'s)? cap",
  "Arm yourself with knowledge",
  "Taking with a grain of salt",
  "Sleep(?:s|es|ed|ing)? on it",
  "Open(?:s|es|ed|ing)? a door",
  "A force to be reckoned with",
  "(?:went|Go) the extra mile",
  "Time flies when having fun",
  "The devil's in the details",
  "(?:went|Go) down in flames",
  "Another string to your bow",
  "Bury your head in the sand",
  "A different kettle of fish",
  "Don't beat around the bush",
  "Cut(?:s|es|ed|ing)? no ice",
  "A big fish in a small pond",
  "It's raining cats and dogs",
  "When life gives you lemons",
  "Home is where the heart is",
  "Climb the corporate ladder",
  "Start(?:s|es|ed|ing)? anew",
  "Act(?:s|es|ed|ing)? of God",
  "Open(?:s|es|ed|ing)? doors",
  "Letting bygones be bygones",
  "Butterflies in the stomach",
  "Shin(?:e|es|ed|ing) bright",
  "Don't count your chickens",
  "Back to the drawing board",
  "The ball is in your court",
  "A penny for your thoughts",
  "Judge a book by its cover",
  "Barking up the wrong tree",
  "Caught between two stools",
  "In the heat of the moment",
  "By the skin of your teeth",
  "Don't cry over spilt milk",
  "A watched pot never boils",
  "By the seat of your pants",
  "Feeling under the weather",
  "Chang(?:e|es|ed|ing) tack",
  "Feather in \\w+(?:'s)? cap",
  "(?:went|Go) with the flow",
  "Cut(?:s|es|ed|ing)? a rug",
  "The calm before the storm",
  "Seeing the bigger picture",
  "Burning the midnight oil",
  "Like a fish out of water",
  "The elephant in the room",
  "You can't have your cake",
  "Curiosity killed the cat",
  "Cry(?:s|es|ed|ing)? wolf",
  "Early bird gets the worm",
  "Born with a silver spoon",
  "(?:went|Go) down a storm",
  "At the top of your lungs",
  "Beauty is Only Skin Deep",
  "Cast pearls before swine",
  "A left-handed compliment",
  "Ace up \\w+(?:'s)? sleeve",
  "Paint with broad strokes",
  "The ball's in your court",
  "Don't throw in the towel",
  "The world is your oyster",
  "In the middle of nowhere",
  "Penny for your thoughts",
  "The best of both worlds",
  "When it rains, it pours",
  "Great minds think alike",
  "Firing on all cylinders",
  "A chip on your shoulder",
  "Batten down the hatches",
  "Every trick in the book",
  "At the end of your rope",
  "Caught in the crossfire",
  "Beating around the bush",
  "Rub(?:s|es|ed|ing)? Off",
  "Skeletons in the closet",
  "(?:went|Go) cold turkey",
  "Life is a rollercoaster",
  "It's not rocket science",
  "Bringing home the bacon",
  "All the world's a stage",
  "Paint the town with joy",
  "A whirlwind of emotions",
  "Fishing for compliments",
  "Turning over a new leaf",
  "Costs an arm and a leg",
  "Like a bat out of hell",
  "Through thick and thin",
  "Crying over spilt milk",
  "Back to the salt mines",
  "Chip off the old block",
  "A blessing in disguise",
  "Bending over backwards",
  "Driving a hard bargain",
  "Don't hold your breath",
  "Can't hold a candle to",
  "A blessing and a curse",
  "Once bitten, twice shy",
  "In the blink of an eye",
  "Not a spark of decency",
  "Water under the bridge",
  "The dog days of summer",
  "On the same wavelength",
  "Lights, camera, action",
  "Light a fire under \\w+",
  "Explore the wilderness",
  "On the path to success",
  "City that never sleeps",
  "Time is of the essence",
  "Opening a can of worms",
  "Exploring new horizons",
  "Volcano about to erupt",
  "Whole world to explore",
  "Extend an olive branch",
  "Raining cats and dogs",
  "Easier said than done",
  "Ball is in your court",
  "It takes two to tango",
  "Off \\w+(?:'s)? rocker",
  "Cat got your tongue\\?",
  "Every nook and cranny",
  "(?:went|Go) for broke",
  "As light as a feather",
  "At the end of the day",
  "Be there or be square",
  "Chip on your shoulder",
  "Every dog has his day",
  "Getting a second wind",
  "A feather in your cap",
  "Behind the eight ball",
  "Blow your own trumpet",
  "Clip \\w+(?:'s)? wings",
  "All hat and no cattle",
  "Calm before the storm",
  "Cat on a hot tin roof",
  "A little bird told me",
  "The luck of the Irish",
  "The icing on the cake",
  "In the great outdoors",
  "Built like a fortress",
  "Every dog has its day",
  "Caught in a whirlwind",
  "Top of the food chain",
  "As cool as a cucumber",
  "Paint a vivid picture",
  "Monkey see, monkey do",
  "A tornado of emotions",
  "Chart your own course",
  "Needle in a haystack",
  "Beat around the bush",
  "At the drop of a hat",
  "Method to my madness",
  "Blessing in disguise",
  "All bark and no bite",
  "A tough nut to crack",
  "All in the same boat",
  "Dressed to the nines",
  "At the eleventh hour",
  "Beating a dead horse",
  "Crossing the Rubicon",
  "Beat a hasty retreat",
  "Cloud on the horizon",
  "A stone's throw away",
  "Benefit of the doubt",
  "Clean bill of health",
  "Stab \\w+ in the back",
  "A snake in the grass",
  "One foot in the door",
  "At the crack of dawn",
  "Breathe down my neck",
  "Under the same stars",
  "Straight as an arrow",
  "Fasten your seatbelt",
  "Like a shooting star",
  "Party like it's 1999",
  "Under the rising sun",
  "In the early morning",
  "In the morning light",
  "In the driver's seat",
  "A rainbow in the sky",
  "Weathering the storm",
  "Flexing your muscles",
  "Down the rabbit hole",
  "Once in a blue moon",
  "Best of both worlds",
  "Bend over backwards",
  "A storm in a teacup",
  "Finger in every pie",
  "As old as the hills",
  "By hook or by crook",
  "Can't hold a candle",
  "All in a day's work",
  "Few and far between",
  "Chomping at the bit",
  "Clutching at straws",
  "Cutting the mustard",
  "Dropping like flies",
  "At sixes and sevens",
  "By leaps and bounds",
  "A fish out of water",
  "Feather in your cap",
  "For crying out loud",
  "From rags to riches",
  "A drop in the ocean",
  "A slap on the wrist",
  "Behind closed doors",
  "Hanging by a thread",
  "On top of the world",
  "Piece of the puzzle",
  "The apple of my eye",
  "Blast from the past",
  "Don't rock the boat",
  "In the light of day",
  "Uncharted territory",
  "Soar to new heights",
  "In the starry night",
  "Fine wine selection",
  "At the break of day",
  "Grasp the main idea",
  "The sky's the limit",
  "Waving a magic wand",
  "In the nick of time",
  "The show must go on",
  "Gift from the heart",
  "Navigate the waters",
  "Under the same moon",
  "Chasing the horizon",
  "Losing your marbles",
  "Sinking or swimming",
  "Climbing the ladder",
  "Carrying the weight",
  "Sleeping like a log",
  "Mapping the journey",
  "Off the beaten path",
  "The tide is turning",
  "Back to square one",
  "Cool as a cucumber",
  "As fit as a fiddle",
  "As happy as a clam",
  "As pale as a ghost",
  "Bigger fish to fry",
  "Bolt from the blue",
  "Clean as a whistle",
  "Beat the pants off",
  "Dead as a doornail",
  "Down for the count",
  "Grasping at straws",
  "A leap in the dark",
  "A tough row to hoe",
  "Catch-22 situation",
  "Ace up your sleeve",
  "Ignorance is bliss",
  "A Shot in the Dark",
  "Cat out of the bag",
  "Knee jerk reaction",
  "Paint the town red",
  "It's a small world",
  "Last but not least",
  "The bigger picture",
  "A storm is brewing",
  "Pedal to the metal",
  "King of the jungle",
  "Star in the making",
  "Shop 'til you drop",
  "Race to the finish",
  "The great outdoors",
  "In the land of nod",
  "A lightbulb moment",
  "Lost in the cosmos",
  "Temperature rising",
  "A bird in the hand",
  "Blow your own horn",
  "Sweeter than honey",
  "Castles in the air",
  "Kicking the bucket",
  "Spilling the beans",
  "Testing the waters",
  "Sounding the alarm",
  "Planting the seeds",
  "Raising a red flag",
  "Seeing the sunrise",
  "Chasing the sunset",
  "Taking a step back",
  "Hitting the target",
  "Counting the stars",
  "Saved by the bell",
  "Under the weather",
  "Fish out of water",
  "Beat a dead horse",
  "Hard nut to crack",
  "A snowball effect",
  "An eye for an eye",
  "As common as dirt",
  "Back to the grind",
  "Bent out of shape",
  "Caught red-handed",
  "Against the grain",
  "Alive and kicking",
  "As happy as Larry",
  "Down in the dumps",
  "Flat as a pancake",
  "Biting the bullet",
  "Catching some Z's",
  "Ahead of the pack",
  "Against the clock",
  "Blow hot and cold",
  "Burst your bubble",
  "As the crow flies",
  "Not my cup of tea",
  "Cream of the crop",
  "Jam on the brakes",
  "Out of your depth",
  "Nip it in the bud",
  "Out of this world",
  "In the lion's den",
  "Weather the storm",
  "Behind sunglasses",
  "Storm in a teacup",
  "Tool of the trade",
  "Lost in the stars",
  "Lost in the woods",
  "Dawn of a new day",
  "The plot thickens",
  "Thread the needle",
  "Luck of the Irish",
  "Feather your nest",
  "Top of the podium",
  "Win-win situation",
  "Behind the scenes",
  "Rake in the money",
  "Blossom and bloom",
  "Chase the sunrise",
  "Gaze at the stars",
  "Genie in a bottle",
  "Built like a tank",
  "Sunny disposition",
  "Breaking the mold",
  "Putting on a show",
  "Shedding light on",
  "Book of knowledge",
  "Race against time",
  "On the same page",
  "An arm and a leg",
  "No pain, no gain",
  "Bury the hatchet",
  "Down to the wire",
  "Grasp the nettle",
  "As busy as a bee",
  "Busy as a beaver",
  "Chew the scenery",
  "As right as rain",
  "Bite your tongue",
  "Champ at the bit",
  "Egg on your face",
  "Flash in the pan",
  "Gone to the dogs",
  "Against all odds",
  "Dyed in the wool",
  "For good measure",
  "Behind the times",
  "Clutch at straws",
  "Devil's Advocate",
  "Old as the hills",
  "Pulling your leg",
  "Climb the ladder",
  "Bright and early",
  "Living the dream",
  "In the same boat",
  "Up in the clouds",
  "In the moonlight",
  "Around the world",
  "Luck of the draw",
  "Over the rainbow",
  "On the same boat",
  "Slow as a turtle",
  "Chase the sunset",
  "Above and beyond",
  "Winner takes all",
  "Slice of the pie",
  "Wizardry at work",
  "Savor the flavor",
  "Select top wines",
  "In the cityscape",
  "Connect the dots",
  "Raindrops of joy",
  "Bump in the road",
  "Food for thought",
  "Hitting the sack",
  "Facing the music",
  "Building bridges",
  "Hitting the road",
  "Turning the page",
  "Chasing rainbows",
  "Full steam ahead",
  "Across the globe",
  "Brighten the day",
  "Bite the bullet",
  "A piece of cake",
  "Out of the blue",
  "Green with envy",
  "Happy as a clam",
  "A stone's throw",
  "As clear as mud",
  "Apple of my eye",
  "Clear as a bell",
  "All Greek to me",
  "Burning bridges",
  "Chewing the fat",
  "Cutting corners",
  "Drawing a blank",
  "Fits and starts",
  "An axe to grind",
  "Be in hot water",
  "Clear the decks",
  "Crocodile tears",
  "Not ring a bell",
  "Flesh and blood",
  "Backseat driver",
  "Dangle a carrot",
  "Full of hot air",
  "Right on target",
  "Top of the line",
  "Bite the burger",
  "The bee's knees",
  "Home sweet home",
  "Ballpark figure",
  "Picture-perfect",
  "Front-page news",
  "Shadow of doubt",
  "The bottom line",
  "Bird's eye view",
  "Plant the seeds",
  "Chasing the sun",
  "Restful slumber",
  "Ship has sailed",
  "Sky's the limit",
  "Packing a punch",
  "Riding the wave",
  "Ace in the hole",
  "A dime a dozen",
  "The last straw",
  "Be on the ball",
  "As cold as ice",
  "As easy as ABC",
  "Bald as a coot",
  "Blind as a bat",
  "Bored to death",
  "Climb the wall",
  "Down the hatch",
  "Face the music",
  "Good Samaritan",
  "At a loose end",
  "Be a long shot",
  "Blow Off Steam",
  "Chase rainbows",
  "At loggerheads",
  "Chuck a wobbly",
  "Round the bend",
  "Black and blue",
  "Shopping spree",
  "Fun in the sun",
  "Smooth sailing",
  "Piece of candy",
  "Pack your bags",
  "A star is born",
  "Loud and clear",
  "Off the charts",
  "Gift with love",
  "Heartfelt gift",
  "Steer clear of",
  "Winning streak",
  "Bird in flight",
  "Shining bright",
  "Piece of cake",
  "Up in the air",
  "When pigs fly",
  "In a nutshell",
  "Full of beans",
  "Hang in there",
  "Bite the dust",
  "Cold shoulder",
  "Busy as a bee",
  "Clear the air",
  "Down to earth",
  "A red herring",
  "Poke the Bear",
  "On cloud nine",
  "Over the moon",
  "Butter \\w+ up",
  "Cheap as dirt",
  "In cold blood",
  "The bombshell",
  "Off the rails",
  "In the desert",
  "Desert island",
  "Wine and dine",
  "Seize the day",
  "Halfway there",
  "Twilight zone",
  "Wounded pride",
  "Off the radar",
  "In your genes",
  "Seal the deal",
  "Taking flight",
  "Rock and roll",
  "New day dawns",
  "In hot water",
  "Far cry from",
  "A hot potato",
  "Chew the fat",
  "Eager beaver",
  "Bone to pick",
  "Clear as mud",
  "Crack a book",
  "Down and out",
  "Elbow grease",
  "Dime a dozen",
  "Feeling blue",
  "An old flame",
  "Apple of Eye",
  "Zip Your Lip",
  "On the fence",
  "Couch potato",
  "Up for grabs",
  "Off the hook",
  "Pack a punch",
  "Stir the pot",
  "Pen a letter",
  "Party pooper",
  "In the files",
  "Juicy burger",
  "Morning glow",
  "Star-studded",
  "Party animal",
  "Sitting duck",
  "Hatch a plan",
  "Suit and tie",
  "Nail it down",
  "Sail through",
  "By the book",
  "On the ball",
  "Easy as pie",
  "Basket case",
  "Bottom line",
  "Eating crow",
  "Fool's gold",
  "A cut above",
  "Dead ringer",
  "Above board",
  "Cold turkey",
  "Can't stand",
  "Chicken out",
  "Forty winks",
  "In the loop",
  "Sour grapes",
  "Green light",
  "Gift of gab",
  "Bright idea",
  "Steer clear",
  "First light",
  "Waxing moon",
  "Waning moon",
  "Hat in hand",
  "At daybreak",
  "Green thumb",
  "In the dark",
  "Drama queen",
  "Binge-watch",
  "City lights",
  "Time flying",
  "Last straw",
  "All thumbs",
  "Cloud nine",
  "For a song",
  "Brainstorm",
  "Time flies",
  "All aboard",
  "Moonstruck",
  "No-go zone",
  "Bull's-eye",
  "Dark horse",
  "Cold feet",
  "Even keel",
  "Acid test",
  "Night owl",
  "Game over",
  "Red light",
  "Full moon",
  "Bullseye!",
  "Fine wine",
  "Fast food",
  "On target",
  "Blast off",
  "Rainy day",
  "All ears",
  "Catch-22",
  "Cakewalk",
  "Chalk up",
  "Cool cat",
  "Notch up",
  "Blackout",
  "Armor up",
  "Bookworm",
  "New moon",
  "Red flag",
  "New dawn",
  "In a fog",
  "Clam up",
  "Blew it",
  "All set",
  "Top hat",
];

export const IDIOM_REPLACEMENTS: string[] = [
  "Hear directly from the source",
  "Experience what you caused",
  "Improvise",
  "Deal with it later",
  "Be stolen",
  "Assume success before it's certain",
  "Trust without proof",
  "Deal with it later",
  "Take advantage of favorable conditions",
  "Be skeptical",
  "Doing everything possible",
  "Take credit",
  "Act on your words",
  "Ignore",
  "Be skeptical",
  "Cause emotional pain",
  "Work hard",
  "Rely on one thing",
  "Focus on essentials",
  "Prevention is better",
  "Get noticed easily",
  "Be thorough and precise",
  "Depart happily or content",
  "Summarize",
  "No matter what",
  "Promise sincerely",
  "Show emotions openly",
  "Allow opportunities to arise",
  "Work hard",
  "Announce widely",
  "Share a meal",
  "Annoy",
  "Solve two problems",
  "Become more outgoing",
  "Do things in the wrong order",
  "Engage in a high-stakes or competitive environment",
  "Improvement after difficulties",
  "Celebrate the beginning of a year",
  "Doing more than required",
  "Person appears",
  "Feel sick",
  "Start",
  "Welcome new possibilities",
  "Negotiate firmly for a good deal",
  "Recognize impending issues",
  "Enter impressively",
  "Don't be too confident",
  "Explode in anger",
  "Certain gain is better",
  "Become known",
  "Experience difficulties",
  "Announce publicly",
  "Reveal a secret",
  "Deal with it later",
  "Be ignored",
  "Do innovative",
  "Perform a surprising feat",
  "Make a good impression",
  "Personalize living space",
  "Celebrate happily",
  "Spoil their plans",
  "Run fast",
  "Better to have less than risk more",
  "No matter what",
  "Annoy greatly",
  "Understand and deal",
  "Express emotions openly",
  "Understand complicated",
  "Express your thoughts openly",
  "Hope for a positive outcome",
  "Embark on exciting journeys",
  "Be exactly right",
  "Hear a rumor",
  "Ignore",
  "Be undecided",
  "Lose energy",
  "Unnoticed observer",
  "Be unique",
  "Risking everything",
  "Postpone plans",
  "Be very expensive",
  "Retribution",
  "Children often resemble their parents",
  "Compare two unlike things",
  "Be the main focus",
  "Appreciate nature",
  "Express oneself clearly",
  "Think creatively or solve a problem",
  "Understand their perspective",
  "Imagine a bright future",
  "Be the center of attention",
  "Dealing with a problem when necessary",
  "Can't have both",
  "Start conversation",
  "Extreme actions needed",
  "Return to start",
  "Very similar",
  "Starting the day in a bad mood",
  "In a dilemma",
  "Ensure the door is shut",
  "Alert others",
  "Early morning",
  "Handle the door with caution",
  "Handle gently",
  "Begin anew",
  "Set a clear boundary",
  "Share openly",
  "Achieve unity",
  "A valuable reward",
  "Continue on the correct path",
  "Understand hidden meaning",
  "Feel ill",
  "Admit error",
  "Argue violently",
  "Difficult situation",
  "stop being responsible for or involved",
  "Forget past offenses and start anew",
  "Start a task with enthusiasm",
  "Dawn",
  "Be heard",
  "Good luck",
  "Don't rely on one thing",
  "Adapt to challenges",
  "Fret over the past",
  "Join others",
  "Cost a lot",
  "Avoid disturbing",
  "Work late",
  "Illegitimate birth",
  "Fail badly",
  "Succeed unexpectedly",
  "Start over",
  "Use opportunities well",
  "Watch carefully",
  "Exercise caution",
  "Complete a task",
  "Change their attitude",
  "Examine thoroughly and exhaustively",
  "Share a meal with each other",
  "Go with the flow",
  "Be creative and innovative",
  "Achieve inner calm",
  "Agree",
  "Worsen a situation",
  "Hide emotion",
  "Earn money",
  "Health advice",
  "Subjective",
  "Fight fiercely",
  "Worsen a situation",
  "Speak frankly",
  "Gain an advantage",
  "Persuade",
  "Sound familiar",
  "Become fit",
  "Appearances can be deceptive",
  "Begin anew",
  "Go with the flow",
  "Discover positive in a negative situation",
  "Protect your stance",
  "Go along with circumstances",
  "Receive a loud applause",
  "Schedule",
  "Near completion",
  "Do things in order",
  "Tease",
  "Regret useless",
  "Looks can be deceiving",
  "Images convey more",
  "Seem innocent",
  "Cost a lot",
  "Hear",
  "Missing increases affection",
  "Buy without full details",
  "Create problems",
  "Aim high",
  "Allow a sudden release or access",
  "Complete a task or assignment",
  "Return to a previous time",
  "Aspire to greatness",
  "Uphold your convictions",
  "Examine details closely",
  "Perform with passion",
  "Cause a public disturbance",
  "Foster camaraderie",
  "Give up",
  "Small part",
  "Cry a lot",
  "Miss the big picture",
  "Don't harm a benefactor",
  "Hope for good luck",
  "Speak without thinking",
  "That's just how things happen",
  "Socialize with others",
  "Set aside money or resources for future needs or emergencies",
  "Surrender",
  "Begin a journey or adventure",
  "Take a firm stand",
  "Aim high",
  "Spoil the mood",
  "Do things in your unique way",
  "Do perfectly",
  "Enter forcefully",
  "Writing has more influence than violence",
  "Hope for improvement",
  "Fresh beginning",
  "Time passes quickly",
  "Stay positive",
  "Similar people group",
  "Small amount",
  "Confess",
  "Taking on too much",
  "Destroy relationships",
  "Images are expressive",
  "Be a thief",
  "Create an impact",
  "Refuse to back down",
  "Achieve great success",
  "Deal with problems as they come",
  "Get the latest news",
  "Set a date",
  "Make a formal written agreement",
  "Close to completion",
  "Get to the point",
  "Be patient",
  "Almost succeeded",
  "Surprise with news",
  "Improvising",
  "Hurt their feelings",
  "Desire the unattainable",
  "Cause initial damage in a conflict",
  "Imminent change",
  "Start writing or creating",
  "Achieve a perfect result",
  "Make a hopeful wish",
  "Mark an occasion happily",
  "Allow access or opportunity",
  "Mental strength overcomes physical challenges",
  "Sleep soundly",
  "Solving two problems at once",
  "Mark an occasion with flair",
  "Do whatever it takes to win",
  "Die",
  "Actions show true intentions",
  "Very healthy",
  "Take on too much",
  "Don't judge by appearance",
  "Accept others' choices",
  "Reveal a secret",
  "Good in bad",
  "Early to succeed",
  "In a difficult situation",
  "Prevent from happening",
  "Descriptive",
  "Looks can be deceiving",
  "Reach standard",
  "Very busy",
  "Saving is beneficial",
  "Overworking",
  "Trusting despite uncertainty",
  "A person who doesn't settle in one place",
  "Almost everything",
  "Directly from the original source",
  "End",
  "Go crazy",
  "Warn of danger",
  "The conclusion",
  "Excel",
  "Gain knowledge or experience",
  "Go off course or deviate from a plan",
  "Watch for carefully",
  "Strive to achieve greatness",
  "Continue a tradition",
  "Conclude or end",
  "Wake up early",
  "Exaggerate sadness",
  "Make decisions",
  "Attract attention",
  "Become comfortable",
  "Very luxurious",
  "Be very dear",
  "Alter opinion",
  "Alter accounts dishonestly",
  "Hope in difficulty",
  "Get sleep",
  "Speak loudly or assertively",
  "Achieve a specific goal or objective",
  "Decide on the spur of the moment",
  "Take on responsibility",
  "Win easily and convincingly",
  "Attain the objective",
  "Solve two problems",
  "Make a global impact",
  "Highlight a potential issue",
  "Revealing a secret",
  "Alert or announce",
  "Miss the chance",
  "Study",
  "Don't know",
  "Stop working",
  "Sleep",
  "Set a limit",
  "Change opinion",
  "Appearances can deceive",
  "Complain about misfortune",
  "Make a mistake",
  "Not as harsh as they appear",
  "Stop working or trying",
  "Take responsibility",
  "Fail to achieve",
  "A great invention or innovation",
  "keep doing or talking about the same thing without achieving anything",
  "Improve relationships",
  "Take a chance",
  "Consistency leads to success",
  "Perform",
  "Avoid trouble or harm",
  "Isolated in an unfamiliar place",
  "Remain focused",
  "Move on to the next phase",
  "Provide opportunities",
  "Too little, too late",
  "Unexpected change",
  "Alter their perspective",
  "Be in control",
  "Don't risk everything",
  "Act too soon",
  "Go to bed",
  "Destroy relationships",
  "Leave",
  "Not mentally sound",
  "Harm a helper",
  "Very fast",
  "Find nothing",
  "Effectively",
  "Experience what you've done to others",
  "Feel sad",
  "become angry or agitated",
  "Fail or succeed",
  "Wake up and be alert",
  "Be suitable",
  "Unchangeable",
  "Evoke emotion",
  "Possess the solution or answer",
  "Go to bed",
  "No chance",
  "Do poorly",
  "The show is over",
  "Nervous",
  "Fixing early avoids more work",
  "Family first",
  "Grudge",
  "A general principle",
  "Purchase a faulty item",
  "Listen carefully",
  "Think carefully and logically",
  "Accelerate or hurry",
  "Make a toast or celebrate",
  "Don't dwell on past mistakes",
  "Being early leads to success",
  "The importance of small things",
  "Very excited or enthusiastic",
  "A notable achievement",
  "Be informed",
  "Not taking it seriously",
  "Delay a decision until the next day",
  "Create an opportunity",
  "Powerful and formidable",
  "Do more",
  "Time passes quickly",
  "Small things matter",
  "Fail spectacularly",
  "Additional skill",
  "Ignore a problem",
  "Completely different",
  "Be direct",
  "Fail to impress",
  "An important person in a small group or organization",
  "Heavy rain",
  "Make the best of a difficult situation",
  "Where you feel most comfortable",
  "Advance in a career",
  "Begin again",
  "Unpredictable event",
  "Create opportunities",
  "Forgiving and starting anew",
  "Feeling nervous or anxious",
  "Excel",
  "Don't expect success early",
  "Start over",
  "Your decision",
  "What are you thinking?",
  "Judge superficially",
  "Mistaken",
  "Difficult choice",
  "Without thinking",
  "Narrowly",
  "Don't regret",
  "Time slows when waiting",
  "Without preparation",
  "Feeling ill",
  "Change approach",
  "Achievement to be proud",
  "Follow the majority",
  "Dance energetically and skillfully",
  "Quiet before trouble",
  "Understanding the overall perspective",
  "Working late",
  "Uncomfortable",
  "Obvious problem ignored",
  "Can't have it all",
  "Dangerous inquiry",
  "Raise a false alarm",
  "First come, first served",
  "Wealthy by birth",
  "Be received very well",
  "Very loudly",
  "Looks vs. Character",
  "Offer value to the unappreciative",
  "Insult disguised as praise",
  "Hidden advantage",
  "Address a topic in a general way",
  "Your responsibility",
  "Don't give up",
  "Abundant opportunities await",
  "A remote location",
  "Ask what's on mind",
  "All advantages",
  "Bad things come in bunches",
  "Similar thoughts",
  "Functioning at maximum capacity",
  "Holding a grudge",
  "Prepare for trouble",
  "Every possible method",
  "Out of patience",
  "Involved in a conflict",
  "Avoiding the main topic",
  "Influence",
  "Hidden secrets",
  "Quit addictive behavior abruptly",
  "Life is full of ups and downs",
  "It's not complicated",
  "Earning a living or providing for the family",
  "Life is like a play",
  "Celebrate joyfully",
  "Overwhelming feelings",
  "Seeking praise",
  "Making a fresh start",
  "Very expensive",
  "Very fast",
  "In all situations",
  "Regretting the unchangeable",
  "Return to work",
  "Like a parent",
  "Good thing that seemed bad",
  "Trying very hard",
  "Negotiating firmly",
  "Don't wait eagerly",
  "Not as good as",
  "Something has both good and bad aspects",
  "Cautious from past experience",
  "Very quickly",
  "Utterly without manners or morals",
  "Past and forgotten",
  "The hot and lazy days of summer",
  "In agreement",
  "Get ready for action",
  "Motivate to act quickly",
  "Venture into nature",
  "Making progress toward a goal",
  "A place with vibrant nightlife",
  "Urgent and important",
  "Creating new problems",
  "Seeking new opportunities",
  "On the verge of losing their temper",
  "A world full of opportunities and possibilities",
  "Make peace",
  "Raining heavily",
  "Hard to do",
  "It's your decision",
  "Need cooperation",
  "Crazy",
  "Why so quiet?",
  "Everywhere",
  "Risk everything",
  "Very light",
  "Ultimately",
  "Must attend",
  "Hold a grudge",
  "Everyone gets a chance",
  "Gaining new energy",
  "Something to be proud",
  "In a difficult position",
  "Brag about yourself",
  "Limit freedom",
  "All talk but no substance",
  "Quiet before chaos",
  "Extremely nervous",
  "I heard from a secret source",
  "Exceptional luck or good fortune",
  "An additional bonus or enhancement",
  "In a natural or outdoor setting",
  "Strong and sturdy",
  "Everyone has a moment of success or achievement",
  "Engulfed in chaos",
  "The best",
  "Very calm and composed",
  "Describe in detail",
  "Imitate others' behavior",
  "Overwhelming feelings",
  "Make your own path in life",
  "Hard to find",
  "Avoid the topic",
  "Immediately",
  "Reason behind actions",
  "Good in bad",
  "All talk, no action",
  "Hard to understand",
  "In the same situation",
  "Very dressed up",
  "Last moment",
  "A futile effort",
  "Passing a point of no return",
  "Leave quickly",
  "Future problem",
  "Very close",
  "Trust without evidence",
  "Health certification",
  "Betray close",
  "Deceitful person",
  "A good introduction",
  "Very early in the morning",
  "Constantly monitor or pressure",
  "Sharing the same destiny",
  "Very honest and direct",
  "Prepare for a journey or challenge",
  "Briefly but brightly",
  "Celebrate enthusiastically",
  "In the morning light",
  "During the dawn",
  "During early daylight",
  "In control",
  "A beautiful sight",
  "Surviving difficult times",
  "Demonstrating your strength or abilities",
  "Entering a strange or complex situation",
  "Rarely",
  "All advantages",
  "Try very hard",
  "An overreaction",
  "Involved in many things",
  "Very old",
  "Any means necessary",
  "Not as good",
  "Typical task",
  "Rare",
  "Impatient to start",
  "Desperate for a solution",
  "Meeting expectations",
  "Collapsing or fainting in large numbers",
  "In confusion",
  "Rapidly",
  "Out of place",
  "A notable achievement",
  "Expression of frustration",
  "From poor to rich",
  "A very small part of much larger",
  "Minor punishment",
  "Done in private",
  "In a very precarious situation",
  "Feeling euphoric",
  "A crucial part of a larger whole",
  "cherished or loved deeply",
  "A reminder of the past",
  "Avoid causing problems or disruptions",
  "During daytime",
  "Unknown and unexplored area",
  "Achieve great success",
  "During the nighttime",
  "A choice of quality wines",
  "At sunrise",
  "Understand the central concept",
  "Unlimited possibilities",
  "Making happen effortlessly",
  "Just in time",
  "Continue despite challenges",
  "Thoughtful present",
  "Manage challenges",
  "Connected despite distance",
  "Pursuing distant goals",
  "Going crazy",
  "Failing or succeeding",
  "Advancing in a career",
  "Bearing a heavy responsibility",
  "Sleeping soundly",
  "Planning the path forward",
  "Away from the usual or popular route",
  "A change in circumstances is occurring",
  "Start over",
  "Calm",
  "Very healthy",
  "Very happy",
  "Very pale",
  "More important things",
  "Unexpected",
  "Very clean",
  "Win easily",
  "Completely dead",
  "Out of action",
  "Desperately searching for a solution",
  "A risky action",
  "A difficult task",
  "No win situation",
  "A hidden advantage",
  "Not knowing is better",
  "Wild Guess",
  "Reveal a secret",
  "Quick, automatic response",
  "Enjoy oneself extravagantly",
  "Frequent encounters with familiar people",
  "Last person is important",
  "Overall perspective",
  "A problematic situation is developing",
  "Give maximum effort or speed",
  "Dominant figure",
  "with great potential",
  "Shop excessively",
  "Compete to complete a task",
  "The natural environment",
  "Sleeping",
  "Sudden realization",
  "Completely confused",
  "Increasing tension or excitement",
  "Something certain",
  "Boast about your achievements",
  "Extremely pleasant",
  "Unrealistic dreams",
  "Dying",
  "Accidentally revealing a secret",
  "Trying out",
  "Warning about a problem",
  "Initiating a process or idea",
  "Warning sign",
  "Witnessing a new beginning",
  "Pursuing the end",
  "Reevaluating or reconsidering",
  "Achieving a goal",
  "Daydreaming or contemplating possibilities",
  "Rescued at the last moment",
  "Feel ill",
  "Out of place",
  "Waste effort",
  "Difficult to understand",
  "Increasing significance",
  "Revenge",
  "Very common",
  "Return to work",
  "Upset",
  "Caught in the act",
  "Contrary to norms",
  "Still active",
  "Very happy",
  "Depressed",
  "Very flat",
  "Enduring a painful experience",
  "Sleeping",
  "Leading",
  "Rushed",
  "Be inconsistent",
  "Shatter illusions",
  "Straight line distance",
  "Not to their liking",
  "The best of a group",
  "Stop suddenly",
  "In a challenging situation",
  "Stop at an early stage",
  "Extraordinary",
  "In a dangerous or challenging situation",
  "Endure difficulties",
  "Concealing emotions or intentions",
  "Minor issue blown out of proportion",
  "Necessary equipment for a job",
  "Extremely fascinated or infatuated",
  "Confused and disoriented",
  "Fresh start",
  "The situation becomes more complex",
  "Navigate a narrow path",
  "Good fortune",
  "Accumulate wealth",
  "First place",
  "A scenario where everyone benefits",
  "The hidden or unseen aspect",
  "Earn a lot",
  "Thrive and flourish",
  "Seek new beginnings",
  "Contemplate the universe",
  "Hidden potential or opportunity",
  "Strong and sturdy",
  "Cheerful attitude",
  "Doing unique",
  "Pretending or acting",
  "Providing clarity or understanding",
  "A source of wisdom and information",
  "Hurry to meet a deadline",
  "Agreeing with each other",
  "Very expensive",
  "Effort brings rewards",
  "Make peace",
  "Last minute",
  "Face a difficulty",
  "Very busy",
  "Very busy",
  "Overact",
  "Perfectly fine",
  "Stay silent",
  "Impatient to start",
  "Embarrassed",
  "Something that's initially impressive but lacks substance",
  "Become very bad",
  "Despite very low probability",
  "Set in their ways",
  "In addition",
  "Outdated",
  "Desperate",
  "Contrarian",
  "Very old",
  "Joking with you",
  "Advance in a career",
  "Early in the morning",
  "Enjoying an ideal or desired lifestyle",
  "In a similar situation",
  "Daydreaming or unrealistic",
  "Under the soft light of the moon",
  "Travel to various places",
  "Random chance",
  "In an idealized world",
  "In the same situation",
  "Moving very slowly",
  "Pursue a dream or goal",
  "More than expected",
  "Complete victory",
  "Share",
  "Exceptional skill or talent",
  "Enjoy the taste",
  "Choose the finest wines",
  "Amidst urban surroundings",
  "Understand a situation by analyzing facts",
  "Happy moments",
  "Temporary obstacle",
  "Something to think",
  "Going to bed",
  "Accepting consequences",
  "Improving relationships",
  "Leaving or departing",
  "Moving on from the past",
  "Pursuing unattainable or unrealistic",
  "Proceeding with maximum effort and determination",
  "Worldwide",
  "Make happy",
  "Endure pain",
  "Very easy",
  "Unexpectedly",
  "Very jealous",
  "Very happy",
  "Very close",
  "Confusing",
  "Very cherished",
  "Very clear",
  "Incomprehensible",
  "Destroying relationships",
  "Chatting",
  "Doing poorly to save time or money",
  "Failing to remember",
  "Irregular bursts of activity",
  "A personal agenda",
  "In trouble",
  "Prepare for action",
  "Fake sadness",
  "Not sound familiar",
  "Family or human nature",
  "who gives unwanted advice",
  "Offer a reward to persuade to do",
  "Boastful or exaggerating",
  "Accurate",
  "The best quality",
  "Take a big bite of food",
  "Excellent",
  "Beloved residence",
  "An approximate number",
  "Ideal and beautiful",
  "Important and widely reported",
  "Uncertainty",
  "The most important point",
  "A broad perspective",
  "Begin a process",
  "Pursuing an elusive goal",
  "Peaceful sleep",
  "Missed an opportunity",
  "Infinite potential",
  "Having a strong effect",
  "Going with the flow of a situation",
  "A hidden advantage",
  "Common",
  "Final problem",
  "Be alert",
  "Very cold",
  "Very simple",
  "Completely bald",
  "Very blind",
  "Extremely bored",
  "Frustrated",
  "Drink",
  "Accept consequences",
  "who helps others",
  "Nothing specific to do",
  "Unlikely to happen",
  "Stress Release",
  "Pursue unlikely dreams",
  "In strong disagreement",
  "Act emotionally",
  "Crazy",
  "Bruised",
  "A short period of excessive spending",
  "Enjoying leisure activities in good weather",
  "Easy progress",
  "Something easy to do",
  "Prepare to leave",
  "becomes famous or successful",
  "Easily understood",
  "Extremely high or exceptional",
  "Give a heartfelt present",
  "A present filled with emotion",
  "Avoid",
  "Continuous success",
  "On the move or exploring new horizons",
  "Standing out and being exceptional",
  "Easy",
  "Uncertain or undecided",
  "Never",
  "Briefly",
  "Energetic",
  "Don't give up",
  "Fail or die",
  "Ignore",
  "Very busy",
  "Remove misunderstanding",
  "Practical",
  "Misleading clue",
  "Provoke",
  "Very happy",
  "Extremely happy",
  "Flatter for a favor",
  "Very inexpensive",
  "Deliberately cruel",
  "A surprising or shocking revelation",
  "Going out of control",
  "In a barren or isolated place",
  "Isolated place",
  "Enjoy a fancy meal and drinks",
  "Make the most of the present",
  "Progress is halfway complete",
  "Uncertain or surreal situation",
  "Hurt ego",
  "Not on anyone's attention",
  "Inherited characteristic",
  "Finalize an agreement",
  "Beginning a new endeavor",
  "Live life with excitement and enthusiasm",
  "Fresh start",
  "In trouble",
  "Very different",
  "Controversial issue",
  "Chat casually",
  "Enthusiastic",
  "Issue to discuss",
  "Confusing",
  "Open a book",
  "Without hope",
  "Hard work",
  "Common",
  "Feeling sad",
  "A past lover",
  "Treasured",
  "Silence",
  "Undecided",
  "A lazy person",
  "Available to anyone",
  "No longer in difficulty or trouble",
  "Strong effect",
  "Create trouble",
  "Write a written message",
  "who spoils the fun",
  "Stored information or documents",
  "A flavorful burger",
  "The early morning light",
  "Featuring famous individuals",
  "Enthusiastic partier",
  "Vulnerable to danger",
  "Develop a strategy",
  "Formal attire",
  "Secure firmly",
  "Easily complete a task",
  "Follow rules exactly",
  "Doing a good job",
  "Very easy",
  "Nervous person",
  "Essential point",
  "Admitting a mistake",
  "Something that seems valuable but is not",
  "Better than others",
  "Exact duplicate",
  "Honest and open",
  "Abrupt stop",
  "Dislike intensely",
  "Withdraw due to fear",
  "Short nap",
  "Informed",
  "Disparaging that is unattainable",
  "Approval to proceed",
  "The ability to speak well",
  "A clever thought or plan",
  "Avoid or",
  "Early morning",
  "Increasing lunar illumination",
  "Decreasing lunar illumination",
  "Humbly asking for help",
  "At the beginning of the day",
  "A talent for gardening",
  "Uninformed or unaware",
  "who exaggerates emotions or situations",
  "Watch multiple episodes in one sitting",
  "Urban nightlife",
  "Time passing quickly",
  "Final problem",
  "Clumsy",
  "Very happy",
  "Very cheaply",
  "Generate ideas",
  "Time passes quickly",
  "Everyone is ready to go or participate",
  "Completely infatuated",
  "Restricted or dangerous area",
  "Precise hit or achievement",
  "An unexpected winner",
  "Nervous",
  "Stable and balanced",
  "Definitive test",
  "A person who is active and alert during the night",
  "The end of a situation",
  "Stop or warning",
  "Maximum lunar illumination",
  "Perfect hit or success",
  "High-quality wine",
  "Quick meal",
  "Accurate or focused",
  "Begin with great enthusiasm",
  "Financial hardship",
  "Listening closely",
  "No-win situation",
  "Very easy",
  "Attribute",
  "Respectfully casual",
  "Achieve",
  "Lose consciousness",
  "Prepare for a challenge or confrontation",
  "A person who loves to read",
  "Beginning of a lunar cycle",
  "A warning sign of a problem",
  "Fresh start",
  "Confused or unclear",
  "Stop talking",
  "Messed up",
  "Completely ready",
  "Formal attire",
];

export const IDIOM_HEAD_BASE: string[] = [
  "hear",
  "get",
  "fly",
  "cross",
  "fall",
  "count",
  "give",
  "cross",
  "make",
  "take",
  "",
  "steal",
  "put",
  "give",
  "take",
  "break",
  "keep",
  "put",
  "get",
  "an",
  "attract",
  "cross",
  "ride",
  "make",
  "come",
  "cross",
  "wear",
  "open",
  "put",
  "shout",
  "break",
  "drive",
  "kill",
  "come",
  "put",
  "swim",
  "break",
  "ring",
  "",
  "speak",
  "feel",
  "get",
  "open",
  "drive",
  "read",
  "make",
  "",
  "fly",
  "a",
  "come",
  "fall",
  "shout",
  "let",
  "",
  "fall",
  "break",
  "pull",
  "put",
  "make",
  "mark",
  "rain",
  "run",
  "bird",
  "come",
  "drive",
  "come",
  "pour",
  "wrap",
  "speak",
  "keep",
  "hit",
  "hit",
  "hear",
  "turn",
  "sit",
  "run",
  "fly",
  "break",
  "",
  "take",
  "break",
  "taste",
  "the",
  "compare",
  "take",
  "enjoy",
  "speak",
  "put",
  "walk",
  "build",
  "steal",
  "",
  "you",
  "break",
  "drastic",
  "come",
  "cut",
  "",
  "between",
  "close",
  "ring",
  "break",
  "open",
  "handle",
  "embark",
  "draw",
  "shout",
  "strike",
  "a",
  "stay",
  "read",
  "feel",
  "eat",
  "fight",
  "caught",
  "wash",
  "let",
  "hit",
  "break",
  "make",
  "break",
  "",
  "roll",
  "cry",
  "jump",
  "cost",
  "let",
  "burn",
  "born",
  "come",
  "come",
  "go",
  "play",
  "keep",
  "stop",
  "cross",
  "sing",
  "leave",
  "break",
  "ride",
  "think",
  "find",
  "see",
  "add",
  "keep",
  "bring",
  "an",
  "beauty",
  "fight",
  "add",
  "call",
  "get",
  "twist",
  "ring",
  "get",
  "not",
  "turn",
  "ride",
  "find",
  "defend",
  "ride",
  "bring",
  "mark",
  "finish",
  "",
  "pull",
  "cry",
  "you",
  "a",
  "butter",
  "cost",
  "get",
  "absence",
  "buy",
  "open",
  "shoot",
  "open",
  "deliver",
  "turn",
  "reach",
  "defend",
  "read",
  "sing",
  "make",
  "share",
  "throw",
  "drop",
  "cry",
  "",
  "",
  "cross",
  "shoot",
  "",
  "rub",
  "save",
  "raise",
  "take",
  "put",
  "shoot",
  "rain",
  "march",
  "hit",
  "kick",
  "the",
  "the",
  "start",
  "time",
  "keep",
  "birds",
  "drop",
  "come",
  "biting",
  "burn",
  "a",
  "have",
  "make",
  "stand",
  "fly",
  "cross",
  "read",
  "mark",
  "put",
  "finish",
  "cut",
  "hold",
  "close",
  "drop",
  "",
  "cut",
  "cry",
  "draw",
  "change",
  "put",
  "hit",
  "wish",
  "celebrate",
  "open",
  "mind",
  "sleep",
  "",
  "celebrate",
  "win",
  "kick",
  "actions",
  "fit",
  "bite",
  "",
  "live",
  "spill",
  "every",
  "the",
  "between",
  "keep",
  "picture",
  "",
  "cut",
  "flat",
  "a",
  "",
  "",
  "a",
  "everything",
  "straight",
  "close",
  "lose",
  "sound",
  "end",
  "shine",
  "learn",
  "jump",
  "keep",
  "aim",
  "carry",
  "close",
  "rise",
  "cry",
  "call",
  "catch",
  "find",
  "fit",
  "be",
  "change",
  "cook",
  "light",
  "catch",
  "raise",
  "hit",
  "play",
  "carry",
  "win",
  "achieve",
  "kill",
  "change",
  "raise",
  "",
  "sound",
  "miss",
  "hit",
  "your",
  "call",
  "catch",
  "draw",
  "change",
  "all",
  "cry",
  "drop",
  "bark",
  "call",
  "carry",
  "miss",
  "best",
  "go",
  "build",
  "roll",
  "slow",
  "put",
  "save",
  "castaway",
  "stay",
  "turn",
  "open",
  "a",
  "twist",
  "change",
  "call",
  "",
  "jump",
  "hit",
  "burn",
  "hit",
  "not",
  "bite",
  "as",
  "draw",
  "for",
  "a",
  "have",
  "lose",
  "sink",
  "rise",
  "fit",
  "set",
  "strike",
  "hold",
  "hit",
  "a",
  "cut",
  "elvis",
  "butterflies",
  "a",
  "blood",
  "chip",
  "rule",
  "buy",
  "lend",
  "use",
  "hit",
  "raise",
  "",
  "early",
  "the",
  "like",
  "a",
  "arm",
  "",
  "sleep",
  "open",
  "a",
  "go",
  "time",
  "the",
  "go",
  "another",
  "bury",
  "a",
  "",
  "cut",
  "a",
  "",
  "when",
  "home",
  "climb",
  "start",
  "act",
  "open",
  "",
  "butterflies",
  "shine",
  "",
  "back",
  "the",
  "a",
  "judge",
  "barking",
  "caught",
  "in",
  "by",
  "",
  "a",
  "by",
  "",
  "change",
  "feather",
  "go",
  "cut",
  "the",
  "",
  "",
  "like",
  "the",
  "you",
  "curiosity",
  "cry",
  "early",
  "born",
  "go",
  "at",
  "beauty",
  "cast",
  "a",
  "ace",
  "paint",
  "the",
  "",
  "the",
  "in",
  "penny",
  "the",
  "when",
  "great",
  "firing",
  "a",
  "batten",
  "every",
  "at",
  "caught",
  "beating",
  "rub",
  "skeletons",
  "go",
  "life",
  "",
  "",
  "all",
  "paint",
  "a",
  "fishing",
  "",
  "costs",
  "like",
  "through",
  "",
  "back",
  "chip",
  "a",
  "bending",
  "",
  "",
  "",
  "a",
  "once",
  "in",
  "not",
  "water",
  "the",
  "on",
  "",
  "light",
  "explore",
  "on",
  "city",
  "time",
  "",
  "exploring",
  "volcano",
  "whole",
  "extend",
  "",
  "easier",
  "ball",
  "it",
  "off",
  "cat",
  "every",
  "go",
  "as",
  "at",
  "be",
  "chip",
  "every",
  "",
  "a",
  "behind",
  "blow",
  "clip",
  "all",
  "calm",
  "cat",
  "a",
  "the",
  "the",
  "in",
  "built",
  "every",
  "caught",
  "top",
  "as",
  "paint",
  "monkey",
  "a",
  "chart",
  "needle",
  "beat",
  "at",
  "method",
  "blessing",
  "all",
  "a",
  "all",
  "dressed",
  "at",
  "beating",
  "",
  "beat",
  "cloud",
  "a",
  "benefit",
  "clean",
  "stab",
  "a",
  "one",
  "at",
  "breathe",
  "under",
  "straight",
  "fasten",
  "like",
  "party",
  "under",
  "in",
  "in",
  "in",
  "a",
  "weathering",
  "flexing",
  "down",
  "once",
  "best",
  "bend",
  "a",
  "finger",
  "as",
  "by",
  "",
  "all",
  "few",
  "chomping",
  "clutching",
  "",
  "",
  "at",
  "by",
  "a",
  "feather",
  "for",
  "from",
  "a",
  "a",
  "behind",
  "hanging",
  "on",
  "piece",
  "the",
  "blast",
  "",
  "in",
  "uncharted",
  "soar",
  "in",
  "fine",
  "at",
  "grasp",
  "the",
  "",
  "in",
  "the",
  "gift",
  "navigate",
  "under",
  "chasing",
  "",
  "",
  "climbing",
  "",
  "",
  "mapping",
  "off",
  "the",
  "back",
  "cool",
  "as",
  "as",
  "as",
  "bigger",
  "bolt",
  "clean",
  "beat",
  "dead",
  "down",
  "grasping",
  "a",
  "a",
  "",
  "ace",
  "ignorance",
  "a",
  "cat",
  "knee",
  "paint",
  "",
  "last",
  "the",
  "a",
  "pedal",
  "king",
  "star",
  "shop",
  "race",
  "the",
  "in",
  "a",
  "lost",
  "temperature",
  "a",
  "blow",
  "sweeter",
  "castles",
  "",
  "",
  "testing",
  "",
  "planting",
  "",
  "",
  "chasing",
  "",
  "",
  "",
  "saved",
  "under",
  "fish",
  "beat",
  "hard",
  "a",
  "an",
  "as",
  "back",
  "bent",
  "caught",
  "against",
  "alive",
  "as",
  "down",
  "flat",
  "biting",
  "",
  "ahead",
  "against",
  "blow",
  "burst",
  "as",
  "not",
  "cream",
  "jam",
  "out",
  "nip",
  "out",
  "in",
  "weather",
  "behind",
  "storm",
  "tool",
  "lost",
  "lost",
  "dawn",
  "the",
  "thread",
  "luck",
  "feather",
  "top",
  "",
  "behind",
  "rake",
  "blossom",
  "chase",
  "gaze",
  "genie",
  "built",
  "sunny",
  "",
  "",
  "shedding",
  "book",
  "race",
  "on",
  "an",
  "no",
  "bury",
  "down",
  "grasp",
  "as",
  "busy",
  "chew",
  "as",
  "bite",
  "champ",
  "egg",
  "flash",
  "gone",
  "against",
  "dyed",
  "for",
  "behind",
  "clutch",
  "",
  "old",
  "",
  "climb",
  "bright",
  "",
  "in",
  "up",
  "in",
  "around",
  "luck",
  "over",
  "on",
  "slow",
  "chase",
  "above",
  "winner",
  "slice",
  "wizardry",
  "savor",
  "select",
  "in",
  "connect",
  "raindrops",
  "bump",
  "food",
  "",
  "facing",
  "",
  "",
  "",
  "chasing",
  "full",
  "across",
  "brighten",
  "bite",
  "a",
  "out",
  "green",
  "happy",
  "a",
  "as",
  "apple",
  "clear",
  "all",
  "",
  "chewing",
  "",
  "",
  "fits",
  "an",
  "be",
  "clear",
  "crocodile",
  "not",
  "flesh",
  "backseat",
  "dangle",
  "full",
  "right",
  "top",
  "bite",
  "the",
  "home",
  "ballpark",
  "",
  "",
  "shadow",
  "the",
  "",
  "plant",
  "chasing",
  "restful",
  "ship",
  "",
  "packing",
  "",
  "ace",
  "a",
  "the",
  "be",
  "as",
  "as",
  "bald",
  "blind",
  "bored",
  "climb",
  "down",
  "face",
  "good",
  "at",
  "be",
  "blow",
  "chase",
  "at",
  "chuck",
  "round",
  "black",
  "shopping",
  "fun",
  "smooth",
  "piece",
  "pack",
  "a",
  "loud",
  "off",
  "gift",
  "heartfelt",
  "steer",
  "",
  "bird",
  "",
  "piece",
  "up",
  "when",
  "in",
  "full",
  "hang",
  "bite",
  "cold",
  "busy",
  "clear",
  "down",
  "a",
  "poke",
  "on",
  "over",
  "butter",
  "cheap",
  "in",
  "the",
  "off",
  "in",
  "desert",
  "wine",
  "seize",
  "halfway",
  "twilight",
  "wounded",
  "off",
  "in",
  "seal",
  "",
  "rock",
  "new",
  "in",
  "far",
  "a",
  "chew",
  "eager",
  "bone",
  "clear",
  "crack",
  "down",
  "elbow",
  "dime",
  "",
  "an",
  "apple",
  "zip",
  "on",
  "couch",
  "up",
  "off",
  "pack",
  "stir",
  "pen",
  "party",
  "in",
  "juicy",
  "morning",
  "",
  "party",
  "",
  "hatch",
  "suit",
  "nail",
  "sail",
  "by",
  "on",
  "easy",
  "basket",
  "bottom",
  "",
  "",
  "a",
  "dead",
  "above",
  "cold",
  "",
  "chicken",
  "forty",
  "in",
  "sour",
  "green",
  "gift",
  "bright",
  "steer",
  "first",
  "waxing",
  "waning",
  "hat",
  "at",
  "green",
  "in",
  "drama",
  "",
  "city",
  "time",
  "last",
  "all",
  "cloud",
  "for",
  "brainstorm",
  "time",
  "all",
  "moonstruck",
  "",
  "",
  "dark",
  "cold",
  "even",
  "acid",
  "night",
  "game",
  "red",
  "full",
  "",
  "fine",
  "fast",
  "on",
  "blast",
  "rainy",
  "all",
  "",
  "cakewalk",
  "chalk",
  "cool",
  "notch",
  "blackout",
  "armor",
  "bookworm",
  "new",
  "red",
  "new",
  "in",
  "clam",
  "blew",
  "all",
  "top",
];
