// Common verbs likely to open a dictionary definition. Used for tense
// agreement in paraphrase.ts ("kicked the bucket" -> "died") and by
// scripts/build-idioms.mjs to pick verb stems (parsed via regex, keep the
// backtick-string format).
export const COMMON_VERBS = new Set(
  `accept act add admit advise agree allow annoy answer appear apply argue ask assume attack attempt avoid become begin behave believe belong blame bother break bring build burn buy call carry catch cause change cheat check choose claim close come commit compare complain complete confirm consider continue control cook cost count cover crash create cross cry cut deal decide defend delay deliver demand deny depend describe destroy die disappear discover discuss do doubt draw dream drink drive drop eat enable encourage end enjoy enter escape exceed excuse exist expect explain explode express fail fall fear feel fight fill find finish fit fix fly follow force forget forgive form get give go grant grow guess happen hate have hear help hide hit hold hope hunt hurry hurt ignore imagine improve include increase inform insist intend invite join joke jump keep kick kill know lack laugh lay lead learn leave lend let lie lift like limit listen live look lose love lower make manage marry match matter mean meet mention mind miss mix move need note notice obey obtain occur offer open operate order overcome owe own pass pay perform permit pick place plan play please point pour praise pray prefer prepare present preserve press pretend prevent proceed produce promise propose protect prove provide pull punish push put quit rain raise reach read realize receive recognize recommend reduce refer reflect refuse regard regret remain remember remind remove repair repeat replace reply report represent require rescue resist resolve respect rest restore return reveal ride ring rise risk rob roll rub ruin rule run rush satisfy save say scare search see seek seem sell send serve set settle shake share shine shoot shout show shut sing sink sit sleep slide slip smell smile smoke solve sound speak speed spell spend spill spin split spoil spread stand stare start state stay steal stick stop store stress stretch strike strive struggle study succeed suffer suggest supply support suppose surprise survive suspect swear sweep swim swing take talk taste teach tease tear tell tempt tend thank think threaten throw tickle tie tire tolerate toss touch train transfer trap travel treat tremble trick trip trust try turn twist understand undo unfold unite unlock upset urge use vanish vary visit vote wait wake walk wander want warn wash waste watch wave wear weep weigh welcome whisper win wish withdraw witness wonder work worry wrap wreck write yell yield be surrender excel embark rely announce improvise harm focus appreciate worsen summarize adapt fret earn confess attract postpone purchase alter exaggerate experience gain influence achieve accelerate possess examine highlight aspire celebrate alert socialize foster aim evoke persuade conclude dance uphold negotiate personalize desire engage ensure handle observe exercise mark attain depart schedule`.split(
    /\s+/,
  ),
);
